# Generated by Django 5.2.7 on 2025-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=16, unique=True)),
                ('player_white_id', models.CharField(max_length=50)),
                ('player_black_id', models.CharField(max_length=50)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('pgn', models.TextField()),
            ],
        ),
    ]
