# Generated by Django 5.2.7 on 2025-10-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_black_id',
            new_name='player_black',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_white_id',
            new_name='player_white',
        ),
    ]
