# Generated by Django 5.2.7 on 2025-10-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_player_black_id_game_player_black_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_black',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_white',
        ),
    ]
