# Generated by Django 5.2.7 on 2025-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_game_player_black_remove_game_player_white'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_played',
        ),
    ]
